import "../styles/globals.css";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        {/* Navbar */}
        <Navbar />
        {/* Sidebar */}
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
